---
title: "Related Variables"
author: "D'Angelo Francis; Nathan Su; Su Yeon Seo"
date: "`r Sys.Date()`"
format: html
embed-resources: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Source: [American National Election Survey Cumulative Data File 1948-2020](https://electionstudies.org/wp-content/uploads/2022/09/anes_timeseries_cdf_codebook_var_20220916.pdf#page=4.76)

**Outcome Variables:**

- VCF0704 - VOTE FOR PRESIDENT- MAJOR CANDIDATES - DEM / REP / 3RD PARTY
- VCF0704a - VOTE FOR PRESIDENT- MAJOR PARTIES - DEM / REP
- VCF0301 - PARTY IDENTIFICATION OF RESPONDENT- 7-POINTSCALE
- VCF0906 - THERMOMETER - DEMOCRATIC HOUSE CANDIDATE
- VCF0907 - THERMOMETER - REPUBLICAN HOUSE CANDIDATE

**Filter Variables:** 

- VCF0004 - YEAR 
- VCF0013 - POST-ELECTION COMPLETION 
- VCF0014 - PRE-ELECTION COMPLETION 
- VCF0748 - VOTED ON ELECTION DAY

**Training Variables by *category*:** 

*Demographic:*

- VCF0101 - RESPONDENT - AGE
- VCF0104 - RESPONDENT - GENDER
- VCF0105b - RACE-ETHNICITY SUMMARY, 4 CATEGORIES
- VCF0110 - RESPONDENT - EDUCATION 4-CATEGORY
- VCF0128 - RESPONDENT - RELIGION MAJOR GROUP
- VCF0147 - RESPONDENT - MARITAL STATUS
- VCF0111 - URBANISM

*Economic Condition:*

- VCF0114 - RESPONDENT FAMILY - INCOME GROUP
- VCF0116 - RESPONDENT - WORK STATUS 7-CATEGORY
- VCF0151 - RESPONDENT - OCCUPATION GROUP 5-CATEGORY
- VCF0146 - RESPONDENT FAMILY - HOME OWNERSHIP
- VCF9224 - IS R INVESTED IN THE STOCK MARKET

*Political Attitudes:*

- VCF0801 - 0894 THERMOMETER INDEX, except:
  - 0827a 
  - 0848a 
  - 0867a 
  - 0875a 
  - 0875b 
  - 0876a 
  - 0877a 
  - 0879a 
  - 0880a 
  - 0880b

- VCF9279 - DOES R CONSIDER SELF TO BE HETEROSEXUAL OR STRAIGHT, HOMOSEXUAL OR [GAY/LESBIAN], OR BISEXUAL
- VCF9280 - DOES R KNOW ANYONE AMONG FAMILY AND FRIENDS WHO IS BISEXUAL OR GAY
- VCF0201 - 0291 THERMOMETER
- VCF9223 - HOW LIKELY IS IT THAT RECENT IMMIGRATION LEVELS WILL TAKE JOBS AWAY FROM PEOPLE ALREADY HERE
- VCF9201 - 9275 CSES: LIKE-DISLIKE (11PT) SCALE PLACEMENT FOR DEMOCRATIC PARTY
- VCF0302 - PARTY IDENTIFICATION OF RESPONDENT- INITIAL PARTYID RESPONSE
- VCF0307 - PARTY IDENTIFICATION OF RESPONDENT’S MOTHER
- VCF0308 - POLITICAL INTEREST OF RESPONDENT’S FATHER
- VCF0338 - 0373  ATTITUDE ON PRESIDENT / CANDIDATE
- VCF0601 - VCF0675 ATTITUDE ON GOVERNMENT OPERATION

*Spatial Information:*

VCF0900 - VCF0901b - CONGRESSIONAL DISTRICT OF RESIDENCE

