---
title: "Final Project Proposal-Revised: Predicting Voter Preference using Demographics"
author: "D'Angelo Francis; Su Yeon Seo; Yuxiang (Nathan) Su"
format: html
embed-resources: true
code-fold: true
toc: true
code-line-numbers: true
---

## Introduction 

Our current project is derived from D'Angelo's prior project proposal and incorporates (or plans to) elements of Su Yeon's proposal and Nathan's proposal. The purpose of this project is to explore how demographics—race, ethnicity, religion, education, etc.— determine how voters vote in elections in the United States.

## Project Methods 

We plan on utilizing a classification regression tree model to predict the probability that a survey respondent voted 'conservatively' or 'liberally'[^1]. Our primary data for analysis and modeling will be survey data from the [American National Election Studies](https://electionstudies.org/), a collaboration between Duke University,the University of Michigan,the University of Texas at Austin (UT Austin), Stanford University, and the National Science Foundation (NSF). We also plan on searching for relevant election exit polls and voter sentiment surveys to supplement the ANES data. 

For our model, we plan on using questions that the ANES asks about a candidate that voter voted for (*e.g., "Which candidate did you vote for in...?"*) as the 'truth'. The goal of our model is to have it precisely predict who a voter voted for using the responses from survey questions asking about policies, such as transgender rights, gun control, reproductive rights, etc. We will incorporate a variable importance analysis to deduce which survey topics and demographic characteristics are the best indicators of voters' candidate preference. 

## Optional Goals 

If time allows, we also plan on modeling voter preference in South Korea using South Korean election data to compare electoral outcomes in the United States and South Korea. Though both countries are culturally distinct, their electoral outcomes have converged towards the right. We are interested in seeing whether the same variables are as importance in South Korea in determining voters' preference.

We would also like to explore voter sentiment on China using the [Asian Barometer](https://www.asianbarometer.org/) survey.

[^1]: We use the terms 'conservatively' or 'liberally' to denote whether a respondent is politically right-leaning or left leaning, respectively. We acknowledge that respondents could consider themselves 'moderate', but for the purpose of this project we will assume a binary choice between 'left-leaning' or 'right-leaning'.